---
- name: Ubuntu Development Playbook
  hosts: localhost
  roles:
    - role: development
      when: development_enabled | bool
    - role: docker
      tags: docker
      when: docker_enabled | bool
    - role: filezilla
      tags: filezilla
      when: filezilla_enabled | bool
    - role: git
      tags: git
      when: git_enabled | bool
    - role: hadolint
      tags: hadolint
      when: hadolint_enabled | bool
    - role: openjdk
      tags:
        - java
        - openjdk
      when: openjdk_enabled | bool
    - role: opentofu
      tags: opentofu
      when: opentofu_enabled | bool
    - role: nodejs
      tags: nodejs
      when: nodejs_enabled | bool
    - role: python
      tags: python
      when: python_enabled | bool
    - role: slack
      tags: slack
      when: slack_enabled | bool
    - role: tflint
      tags: tflint
      when: tflint_enabled | bool
    - role: vagrant
      tags: vagrant
      when: vagrant_enabled | bool
